export enum TaskStatus {
    CREATED = "CREATED",
    IN_PROGRESS = "IN_PROGRESS",
    COMPLETED = "COMPLETED",
    REQUEST_CHANGE = "REQUEST_CHANGE",
    IS_EXPIRED = "IS_EXPIRED",
    IS_DIRECT_BOUNTY = "IS_DIRECT_BOUNTY",
}
